baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Luiz Peixoto"
  subtitle    = "Advocacia e Consultoria"

  cover       = "down/buildings.jpg"
  description = "Here is a description of your site."
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  twitterName = "@adv_luizpeixoto"
  fbName = "luizpeixoto.adv"
  githubName = "p31x070"

  logo = ""
  orgName = "Luiz Peixoto"
  orgWebsite = "https://www.luizpeixoto.com"
  orgDescription = ""

  author = "Luiz Peixoto"
  authorAvatar = "down/Avatar.jpeg"
  authorLocation = "Rio de Janeiro, BR"
  authorWebsite = "https://github.com/p31x070"
  authorDescription = "OABRJ 94719"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "Início"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Primeiros Passos"
  url = "/tags/Iniciar/"
  weight = 100

[[menu.main]]
  name = "Importante"
  url = "/categories/comunicação/"
  weight = 99

[[menu.main]]
  name = "Segurança Digital"
  url = "/tags/segurança"
  weight = 95
